### ISSUE TITLE
Unable to build swift-2.0 branch in Xcode 7 beta 4

### ISSUE THREAD

**Issue by mbuff24** [ViacomInc/Router#11]
@ollieatkinson were you able to run the tests in the swift 2.0 branch in xcode 7 beta 4?

**Comment by ollieatkinson** [comment]
@mbuff24 I believe theres an issue with one of the compiler settings or the pods themselves - I will investigate into this.

**Comment by ollieatkinson** [comment]
@mbuff24 I created a basic example project and Quick & Nimble fails, I will submit the sample project and file a bug report against their branch but I do not believe they will see much value in pursuing this until Xcode is out of beta.

I believe they have the code available for Xcode 7 beta 2

**Comment by ollieatkinson** [comment]
@mbuff24 looks like we need to use 

```ruby
  pod 'Quick',  '= 0.5.1'
  pod 'Nimble', '= 2.0.0-rc.2'
```

**Comment by mbuff24** [comment]
Thanks @ollieatkinson ! closing this one out.
