### ISSUE TITLE
Merge 2.0 into development

### ISSUE THREAD

**Issue by ollieatkinson** [ViacomInc/Router#16]
Since Xcode 7 is no longer in beta can we merge the code onto development?

**Comment by mbuff24** [comment]
hey @ollieatkinson I plan to do a bigger refactor over the next couple of days. I'll open up a PR when it's ready

**Comment by ollieatkinson** [comment]
Ok, let me know I can look over with a review if you want

**Comment by mbuff24** [comment]
hey @ollieatkinson, I did another round of refactoring. Please let me know what you think

thanks

**Comment by ollieatkinson** [comment]
Merged
